config/routes.rb
BFluent::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :toeictests, only: [:new, :create, :destroy]
  resources :casecs, only: [:new, :create, :destroy]
  resources :toeflis, only: [:new, :create, :destroy]
  resources :ielts, only: [:new, :create, :destroy]
  resources :bridges, only: [:new, :create, :destroy]
  resources :toeicsws, only: [:new, :create, :destroy]
  resources :eikens, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/toeic_input', to: 'toeictests#new'
  match '/toeic_journal', to: 'toeictests#toeicjournal'
  match '/casec_input', to: 'casecs#new'
  match '/casec_journal', to: 'casecs#casecjournal'
  match '/toefli_input', to: 'toeflis#new'
  match '/toefli_journal', to: 'toeflis#toeflijournal'
  match '/ielt_input', to: 'ielts#new'
  match '/ielt_journal', to: 'ielts#ieltjournal'
  match '/bridge_input', to: 'bridges#new'
  match '/bridge_journal', to: 'bridges#bridgejournal'
  match '/toeicsw_input', to: 'toeicsws#new'
  match '/toeicsw_journal', to: 'toeicsws#toeicswjournal'
  match '/eiken_input', to: 'eikens#new'
  match '/eiken_journal', to: 'eikens#eikenjournal'
  match '/contact' => 'contact#new', :as => 'contact', :via => :get
  match '/contact' => 'contact#create', :as => 'contact', :via => :post

  match '/about',   to: 'static_pages#about'
  match '/principles',    to: 'static_pages#principles'
  match '/pricing',    to: 'static_pages#pricing'

 

end

app/views/shared/_bridge_form.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>

<div class="container">
	      <div class="row">
              <div class="span3">
        	    <div class="well">
                <%= image_tag("BigB2.png", alt: "BiFluent 'B' logo") %>
                </div>
              </div>
              <div class="span9">
               <div class="well">
               	 <h1>TOEIC® Bridge</h1>
                 <%= form_for(@bridge) do |f| %>
                 <%= render 'shared/error_messages', object: f.object %>
                 <div class="span3">
                 <p><label for="date"><%=t :test_date %></label></p> 
                 <%= f.datepicker :bridge_date %>
                 </div>
                 <div class="span5">
                 <p><label for="amount_bone">TOEIC®のリスニングスコア (5点の刻み値):</label></p>
                 <div id="slider_bone" class="slider"></div>
	             <div id="amount_bone" class="slider_num">60</div>
	             <p><label for="amount_btwo">TOEIC® Bridgeのリーディングスコア (5点の刻み値):</label></p>
                 <div id="slider_btwo"></div>
                 <div id="amount_btwo" class="slider_num" />60</div>
             </div>
                 <%= f.hidden_field :bridge_l %>
                 <%= f.hidden_field :bridge_r %>
                 <div class="center"><%= f.submit I18n.t(:input_bridge), class: "btn btn-large btn-primary" %></div>
                 <% end %>
                </div>
              </div> 
           </div>
</div>

<script>
$(document).ready(function() {
	$(function() {
		$( "#slider_bone" ).slider({
			value: 60,
			min: 10,
			max: 90,
			step: 2,
			slide: function( event, ui ) {
				$( "#amount_bone" ).html( ui.value );
			},

			change: function(event, ui) {
            $('input#bridge_bridge_l').val(ui.value);
            }
		});
		$( "#amount_bone" ).val( $( "#slider_bone" ).slider( "value" ) );
	});

	$(function() {
		$( "#slider_btwo" ).slider({
			value: 60,
			min: 10,
			max: 90,
			step: 2,
			slide: function( event, ui ) {
				$( "#amount_btwo" ).html( ui.value );
			},

			change: function(event, ui) {
            $('input#bridge_bridge_r').val(ui.value);
            }
		});
		$( "#amount_btwo" ).val( $( "#slider_btwo" ).slider( "value" ) );
	});

	$(function() {
		$( "#datepicker" ).datepicker();
		$.datepicker.regional['ja'] = {
		closeText: '閉じる',
		prevText: '&#x3c;前',
		nextText: '次&#x3e;',
		currentText: '今日',
		monthNames: ['1月','2月','3月','4月','5月','6月',
		'7月','8月','9月','10月','11月','12月'],
		monthNamesShort: ['1月','2月','3月','4月','5月','6月',
		'7月','8月','9月','10月','11月','12月'],
		dayNames: ['日曜日','月曜日','火曜日','水曜日','木曜日','金曜日','土曜日'],
		dayNamesShort: ['日','月','火','水','木','金','土'],
		dayNamesMin: ['日','月','火','水','木','金','土'],
		weekHeader: '週',
		dateFormat: 'yy/mm/dd',
		firstDay: 0,
		isRTL: false,
		showMonthAfterYear: true,
		yearSuffix: '年'};
	$.datepicker.setDefaults($.datepicker.regional['ja']);
	});
});
</script>

app/views/shared/_casec_form.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>

<div class="container">
	      <div class="row">
              <div class="span3">
        	    <div class="well">
                <%= image_tag("signin_image.png", alt: "BiFluent CASEC") %>
                </div>
              </div>
              <div class="span9">
               <div class="well">
               	 <h1>CASEC</h1>
                 <%= form_for(@casec) do |f| %>
                 <%= render 'shared/error_messages', object: f.object %>
                 <div class="span3">
                 <p><label for="date"><%=t :xc_date %></label></p> 
                 <%= f.datepicker :c_date %>
                 </div>
                 <div class="span5">
                 <p><label for="amount_one"><%=t :xc_one %>:</label></p>
                 <div id="slider_one"></div>
	             <div id="amount_one" class="slider_num">200</div>
	             <p><label for="amount_two"><%=t :xc_two %>:</label></p>
                 <div id="slider_two"></div>
                 <div id="amount_two" class="slider_num" />200</div>
                 <p><label for="amount_three"><%=t :xc_three %>:</label></p>
                 <div id="slider_three"></div>
                 <div id="amount_three" class="slider_num" />200</div>
                 <p><label for="amount_four"><%=t :xc_four %>:</label></p>
                 <div id="slider_four"></div>
                 <div id="amount_four" class="slider_num" />200</div>
             </div>
                 <%= f.hidden_field :c_one %>
                 <%= f.hidden_field :c_two %>
                 <%= f.hidden_field :c_three %>
                 <%= f.hidden_field :c_four %>
                 <div class="center"><%= f.submit I18n.t(:input_casec), class: "btn btn-large btn-primary" %></div>
                 <% end %>
                </div>
              </div> 
           </div>
</div>

<script>
$(document).ready(function() {
	$(function() {
		$( "#slider_one" ).slider({
			value: 150,
			min: 0,
			max: 250,
			step: 1,
			slide: function( event, ui ) {
				$( "#amount_one" ).html( ui.value );
			},

			change: function(event, ui) {
            $('input#casec_c_one').val(ui.value);
            }
		});
		$( "#amount_one" ).val( $( "#slider_one" ).slider( "value" ) );
	});

	$(function() {
		$( "#slider_two" ).slider({
			value: 150,
			min: 0,
			max: 250,
			step: 1,
			slide: function( event, ui ) {
				$( "#amount_two" ).html( ui.value );
			},

			change: function(event, ui) {
            $('input#casec_c_two').val(ui.value);
            }
		});
		$( "#amount_two" ).val( $( "#slider_two" ).slider( "value" ) );
	});

	$(function() {
		$( "#slider_three" ).slider({
			value: 150,
			min: 0,
			max: 250,
			step: 1,
			slide: function( event, ui ) {
				$( "#amount_three" ).html( ui.value );
			},

			change: function(event, ui) {
            $('input#casec_c_three').val(ui.value);
            }
		});
		$( "#amount_three" ).val( $( "#slider_three" ).slider( "value" ) );
	});

	$(function() {
		$( "#slider_four" ).slider({
			value: 150,
			min: 0,
			max: 250,
			step: 1,
			slide: function( event, ui ) {
				$( "#amount_four" ).html( ui.value );
			},

			change: function(event, ui) {
            $('input#casec_c_four').val(ui.value);
            }
		});
		$( "#amount_four" ).val( $( "#slider_four" ).slider( "value" ) );
	});

	$(function() {
		$( "#datepicker" ).datepicker();
		$.datepicker.regional['ja'] = {
		closeText: '閉じる',
		prevText: '&#x3c;前',
		nextText: '次&#x3e;',
		currentText: '今日',
		monthNames: ['1月','2月','3月','4月','5月','6月',
		'7月','8月','9月','10月','11月','12月'],
		monthNamesShort: ['1月','2月','3月','4月','5月','6月',
		'7月','8月','9月','10月','11月','12月'],
		dayNames: ['日曜日','月曜日','火曜日','水曜日','木曜日','金曜日','土曜日'],
		dayNamesShort: ['日','月','火','水','木','金','土'],
		dayNamesMin: ['日','月','火','水','木','金','土'],
		weekHeader: '週',
		dateFormat: 'yy/mm/dd',
		firstDay: 0,
		isRTL: false,
		showMonthAfterYear: true,
		yearSuffix: '年'};
	$.datepicker.setDefaults($.datepicker.regional['ja']);
	});
});
</script>

app/views/shared/_eiken_form.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>

<div class="container">
	      <div class="row">
              <div class="span3">
        	    <div class="well">
                <%= image_tag("BigB2.png", alt: "BiFluent 'B' logo") %>
                </div>
              </div>
              <div class="span9">
               <div class="well">
               	 <h1>STEP 英検</h1>
                 <%= form_for(@eiken) do |f| %>
                 <%= render 'shared/error_messages', object: f.object %>
                 <div class="span3">
                   <p><label for="date"><%=t :test_date %></label></p> 
                   <%= f.datepicker :eiken_date %>
                 </div>
                 <div class="span5">
                <%= f.select :eiken_level, options_for_select([['5級', 7], ['4級', 6], ['3級', 5], ['準2級', 4], ['2級', 3], ['準1級', 2], ['1級', 1]]), :prompt => 'レベルを選んでください。' %>
                <%= f.select :eiken_result, options_for_select([['合格', true], ['不合格', false]], true) %>
                 </div>
                 <div class="center"><%= f.submit I18n.t(:input_eiken), class: "btn btn-large btn-primary" %></div>
                 <% end %>
                </div>
              </div> 
           </div>
</div>

<script>
$(document).ready(function() {
	$(function() {
		$( "#datepicker" ).datepicker();
		$.datepicker.regional['ja'] = {
		closeText: '閉じる',
		prevText: '&#x3c;前',
		nextText: '次&#x3e;',
		currentText: '今日',
		monthNames: ['1月','2月','3月','4月','5月','6月',
		'7月','8月','9月','10月','11月','12月'],
		monthNamesShort: ['1月','2月','3月','4月','5月','6月',
		'7月','8月','9月','10月','11月','12月'],
		dayNames: ['日曜日','月曜日','火曜日','水曜日','木曜日','金曜日','土曜日'],
		dayNamesShort: ['日','月','火','水','木','金','土'],
		dayNamesMin: ['日','月','火','水','木','金','土'],
		weekHeader: '週',
		dateFormat: 'yy/mm/dd',
		firstDay: 0,
		isRTL: false,
		showMonthAfterYear: true,
		yearSuffix: '年'};
	$.datepicker.setDefaults($.datepicker.regional['ja']);
	});
});
</script>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      <% if I18n.locale == :ja %>
      このフォームは<%= object.errors.count %>個のエラーがあります。
      <% else %>
      The form contains <%= pluralize(object.errors.count, "error") %>.
      <% end %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
</li>

app/views/shared/_ielt_form.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>

<div class="container">
	      <div class="row">
              <div class="span3">
        	    <div class="well">
                <%= image_tag("BigB2.png", alt: "BiFluent 'B' logo") %>
                </div>
              </div>
              <div class="span9">
               <div class="well">
               	 <h1>IELTS</h1>
                 <%= form_for(@ielt) do |f| %>
                 <%= render 'shared/error_messages', object: f.object %>
                 <div class="span3">
                 <p><label for="date"><%=t :test_date %></label></p> 
                 <%= f.datepicker :ielt_date %>
                 </div>
                 <div class="span5">
                 <p><label for="amount_one">IELTS Score:</label></p>
                 <div id="slider_ielt" class="slider"></div>
	             <div id="ielt_one" class="slider_num">6</div>
	             
             </div>
                 <%= f.hidden_field :ielt_score %>
                 <div class="center"><%= f.submit I18n.t(:input_ielt), class: "btn btn-large btn-primary" %></div>
                 <% end %>
                </div>
              </div> 
           </div>
</div>

<script>
$(document).ready(function() {
	$(function() {
		$( "#slider_ielt" ).slider({
			value: 6,
			min: 0,
			max: 9,
			step: 0.5,
			slide: function( event, ui ) {
				$( "#ielt_one" ).html( ui.value );
			},

			change: function(event, ui) {
            $('input#ielt_ielt_score').val(ui.value);
            }
		});
		$( "#ielt_one" ).val( $( "#slider_ielt" ).slider( "value" ) );
	});

	$(function() {
		$( "#datepicker" ).datepicker();
		$.datepicker.regional['ja'] = {
		closeText: '閉じる',
		prevText: '&#x3c;前',
		nextText: '次&#x3e;',
		currentText: '今日',
		monthNames: ['1月','2月','3月','4月','5月','6月',
		'7月','8月','9月','10月','11月','12月'],
		monthNamesShort: ['1月','2月','3月','4月','5月','6月',
		'7月','8月','9月','10月','11月','12月'],
		dayNames: ['日曜日','月曜日','火曜日','水曜日','木曜日','金曜日','土曜日'],
		dayNamesShort: ['日','月','火','水','木','金','土'],
		dayNamesMin: ['日','月','火','水','木','金','土'],
		weekHeader: '週',
		dateFormat: 'yy/mm/dd',
		firstDay: 0,
		isRTL: false,
		showMonthAfterYear: true,
		yearSuffix: '年'};
	$.datepicker.setDefaults($.datepicker.regional['ja']);
	});
});
</script>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <div class="btn-toolbar">
                  <%= link_to "BiFluentのテスト", "#", class: "btn btn-danger" %>
                  </br>
                  <div class="btn-group"> 
                  <a class="btn btn-danger dropdown-toggle" data-toggle="dropdown" href="#">
                  スコアを入れて
                  <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                  <li><%= link_to 'TOEIC®', toeic_input_path %></li>
                  <li><%= link_to 'STEP 英検', eiken_input_path %></li>
                  <li><%= link_to 'TOEFL® iBT', toefli_input_path %></li>
                  <li><%= link_to 'CASEC', casec_input_path %></li>
                  <li><%= link_to 'IELTS', ielt_input_path %></li>
                  <li><%= link_to 'TOEIC® Bridge', bridge_input_path %></li>
                  <li><%= link_to 'TOEIC® SW', toeicsw_input_path %></li>
                  </ul>
                  </div>
                  </div>
              <li class="nav-header">勉強手帳</li>
              <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "BiFluent", root_path %></li>
              <li class="<%= 'active' if current_page?(toeic_journal_path) %>"><%= link_to "TOEIC®", toeic_journal_path %></li>
              <li class="<%= 'active' if current_page?(eiken_journal_path) %>"><%= link_to "STEP 英検", eiken_journal_path %></li>
              <li class="<%= 'active' if current_page?(toefli_journal_path) %>"><%= link_to "TOEFL® iBT", toefli_journal_path %></li>
              <li class="<%= 'active' if current_page?(casec_journal_path) %>"><%= link_to "CASEC", casec_journal_path %></li>
              <li class="<%= 'active' if current_page?(ielt_journal_path) %>"><%= link_to "IELTS", ielt_journal_path %></li>
              <li class="<%= 'active' if current_page?(bridge_journal_path) %>"><%= link_to "TOEIC® Bridge", bridge_journal_path %></li>
              <li class="<%= 'active' if current_page?(toeicsw_journal_path) %>"><%= link_to "TOEIC® SW", toeicsw_journal_path %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->

app/views/shared/_toefli_form.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>

<div class="container">
	      <div class="row">
              <div class="span3">
        	    <div class="well">
                <%= image_tag("BigB2.png", alt: "BiFluent 'B' logo") %>
                </div>
              </div>
              <div class="span9">
               <div class="well">
               	 <h1>TOEFL® iBT</h1>
                 <%= form_for(@toefli) do |f| %>
                 <%= render 'shared/error_messages', object: f.object %>
                 <div class="span3">
                 <p><label for="date"><%=t :test_date %></label></p> 
                 <%= f.datepicker :toefli_date %>
                 </div>
                 <div class="span5">
                 <p><label for="toefli_one">TOEFL® iBT Reading:</label></p>
                 <div id="slider_toeflione" class="slider"></div>
	             <div id="toefli_one" class="slider_num">20</div>
	             <p><label for="toefli_two">TOEFL® iBT Writing:</label></p>
                 <div id="slider_toeflitwo"></div>
                 <div id="toefli_two" class="slider_num" />20</div>
                 <p><label for="toefli_three">TOEFL® iBT Listening:</label></p>
                 <div id="slider_toeflithree"></div>
                 <div id="toefli_three" class="slider_num" />20</div>
                 <p><label for="toefli_four">TOEFL® iBT Speaking:</label></p>
                 <div id="slider_toeflifour"></div>
                 <div id="toefli_four" class="slider_num" />20</div>
             </div>
                 <%= f.hidden_field :toefli_r %>
                 <%= f.hidden_field :toefli_w %>
                 <%= f.hidden_field :toefli_l %>
                 <%= f.hidden_field :toefli_s %>
                 <div class="center"><%= f.submit I18n.t(:input_toefli), class: "btn btn-large btn-primary" %></div>
                 <% end %>
                </div>
              </div> 
           </div>
</div>

<script>
$(document).ready(function() {
	$(function() {
		$( "#slider_toeflione" ).slider({
			value: 20,
			min: 0,
			max: 30,
			step: 1,
			slide: function( event, ui ) {
				$( "#toefli_one" ).html( ui.value );
			},

			change: function(event, ui) {
            $('input#toefli_toefli_r').val(ui.value);
            }
		});
		$( "#toefli_one" ).val( $( "#slider_toeflione" ).slider( "value" ) );
	});

	$(function() {
		$( "#slider_toeflitwo" ).slider({
			value: 20,
			min: 0,
			max: 30,
			step: 1,
			slide: function( event, ui ) {
				$( "#toefli_two" ).html( ui.value );
			},

			change: function(event, ui) {
            $('input#toefli_toefli_w').val(ui.value);
            }
		});
		$( "#toefli_two" ).val( $( "#slider_toeflitwo" ).slider( "value" ) );
	});

	$(function() {
		$( "#slider_toeflithree" ).slider({
			value: 20,
			min: 0,
			max: 30,
			step: 1,
			slide: function( event, ui ) {
				$( "#toefli_three" ).html( ui.value );
			},

			change: function(event, ui) {
            $('input#toefli_toefli_l').val(ui.value);
            }
		});
		$( "#toefli_three" ).val( $( "#slider_toeflithree" ).slider( "value" ) );
	});

	$(function() {
		$( "#slider_toeflifour" ).slider({
			value: 20,
			min: 0,
			max: 30,
			step: 1,
			slide: function( event, ui ) {
				$( "#toefli_four" ).html( ui.value );
			},

			change: function(event, ui) {
            $('input#toefli_toefli_s').val(ui.value);
            }
		});
		$( "#toefli_four" ).val( $( "#slider_toeflifour" ).slider( "value" ) );
	});

	$(function() {
		$( "#datepicker" ).datepicker();
		$.datepicker.regional['ja'] = {
		closeText: '閉じる',
		prevText: '&#x3c;前',
		nextText: '次&#x3e;',
		currentText: '今日',
		monthNames: ['1月','2月','3月','4月','5月','6月',
		'7月','8月','9月','10月','11月','12月'],
		monthNamesShort: ['1月','2月','3月','4月','5月','6月',
		'7月','8月','9月','10月','11月','12月'],
		dayNames: ['日曜日','月曜日','火曜日','水曜日','木曜日','金曜日','土曜日'],
		dayNamesShort: ['日','月','火','水','木','金','土'],
		dayNamesMin: ['日','月','火','水','木','金','土'],
		weekHeader: '週',
		dateFormat: 'yy/mm/dd',
		firstDay: 0,
		isRTL: false,
		showMonthAfterYear: true,
		yearSuffix: '年'};
	$.datepicker.setDefaults($.datepicker.regional['ja']);
	});
});
</script>

app/views/shared/_toeicsw_form.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>

<div class="container">
	      <div class="row">
              <div class="span3">
        	    <div class="well">
                <%= image_tag("BigB2.png", alt: "BiFluent 'B' logo") %>
                </div>
              </div>
              <div class="span9">
               <div class="well">
               	 <h1>TOEIC® SW</h1>
                 <%= form_for(@toeicsw) do |f| %>
                 <%= render 'shared/error_messages', object: f.object %>
                 <div class="span3">
                 <p><label for="date"><%=t :test_date %></label></p> 
                 <%= f.datepicker :toeicsw_date %>
                 </div>
                 <div class="span5">
                 <p><label for="amount_swone">TOEIC® SWのスピーキングスコア:</label></p>
                 <div id="slider_swone" class="slider"></div>
	             <div id="amount_swone" class="slider_num">150</div>
	             <p><label for="amount_swtwo">TOEIC® SWのライティングスコア:</label></p>
                 <div id="slider_swtwo"></div>
                 <div id="amount_swtwo" class="slider_num" />150</div>
             </div>
                 <%= f.hidden_field :toeicsw_s %>
                 <%= f.hidden_field :toeicsw_w %>
                 <div class="center"><%= f.submit I18n.t(:input_toeicsw), class: "btn btn-large btn-primary" %></div>
                 <% end %>
                </div>
              </div> 
           </div>
</div>

<script>
$(document).ready(function() {
	$(function() {
		$( "#slider_swone" ).slider({
			value: 150,
			min: 0,
			max: 200,
			step: 10,
			slide: function( event, ui ) {
				$( "#amount_swone" ).html( ui.value );
			},

			change: function(event, ui) {
            $('input#toeicsw_toeicsw_s').val(ui.value);
            }
		});
		$( "#amount_swone" ).val( $( "#slider_swone" ).slider( "value" ) );
	});

	$(function() {
		$( "#slider_swtwo" ).slider({
			value: 150,
			min: 0,
			max: 200,
			step: 10,
			slide: function( event, ui ) {
				$( "#amount_swtwo" ).html( ui.value );
			},

			change: function(event, ui) {
            $('input#toeicsw_toeicsw_w').val(ui.value);
            }
		});
		$( "#amount_swtwo" ).val( $( "#slider_swtwo" ).slider( "value" ) );
	});

	$(function() {
		$( "#datepicker" ).datepicker();
		$.datepicker.regional['ja'] = {
		closeText: '閉じる',
		prevText: '&#x3c;前',
		nextText: '次&#x3e;',
		currentText: '今日',
		monthNames: ['1月','2月','3月','4月','5月','6月',
		'7月','8月','9月','10月','11月','12月'],
		monthNamesShort: ['1月','2月','3月','4月','5月','6月',
		'7月','8月','9月','10月','11月','12月'],
		dayNames: ['日曜日','月曜日','火曜日','水曜日','木曜日','金曜日','土曜日'],
		dayNamesShort: ['日','月','火','水','木','金','土'],
		dayNamesMin: ['日','月','火','水','木','金','土'],
		weekHeader: '週',
		dateFormat: 'yy/mm/dd',
		firstDay: 0,
		isRTL: false,
		showMonthAfterYear: true,
		yearSuffix: '年'};
	$.datepicker.setDefaults($.datepicker.regional['ja']);
	});
});
</script>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.toeictests.count, "TOEIC Tests") %>
</span>